defaults:
  - data_preparing_config_schema
  - dataset_reader_manager: ghc_jigsaw_twitter
  - dataset_cleaner_manager: simple_dataset_cleaner
  
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: disabled
  
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

data_version: v3
access_token_secret_version: "1"