services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-jeffrey}"
    image: cyberbullying-data-preparation
    container_name: cyberbullying-data-preparation-container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/e2eml-jiho-430901-82abb03a70c5.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-jihoahn}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud:/home/${USER_NAME}/.config/gcloud
      - ~/.config/dask:/home/${USER_NAME}/.config/dask
    ports:
      - 8888:8888
    ipc: host
    init: true

