access_token_secret_version: '1'
dask_cluster:
  _target_: dask_cloudprovider.gcp.GCPCluster
  asynchronous: null
  debug: false
  disk_type: pd-standard
  docker_image: asia-northeast3-docker.pkg.dev/e2eml-jiho-430901/cyberbullying/data-processing:8efccafe-80f0-4cb6-8db6-e8438ee58358
  env_vars: {}
  extra_bootstrap:
  - gcloud auth configure-docker --quiet asia-northeast3-docker.pkg.dev
  filesystem_size: 50
  gpu_type: null
  instance_labels: {}
  machine_type: n1-standard-1
  n_workers: 3
  network: default
  network_projectid: e2eml-jiho-430901
  ngpus: 0
  on_host_maintenance: TERMINATE
  preemptible: false
  projectid: e2eml-jiho-430901
  scheduler_options: {}
  security: true
  silence_logs: null
  source_image: projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2004-focal-v20240822
  worker_class: dask.distributed.Nanny
  worker_options:
    nthreads: 1
  zone: asia-northeast3-c
data_local_save_dir: ./data/raw
data_version: v3
dataset_cleaner_manager:
  _target_: jeffrey.data_processing.dataset_cleaners.DatasetCleanerManager
  dataset_cleaners:
    new_line:
      _target_: jeffrey.data_processing.dataset_cleaners.NewLineCharacterDatasetCleaner
    non_ascii:
      _target_: jeffrey.data_processing.dataset_cleaners.NonASCIIDatasetCleaner
    non_letters:
      _target_: jeffrey.data_processing.dataset_cleaners.NonLettersDatasetCleaner
    punctuation:
      _target_: jeffrey.data_processing.dataset_cleaners.PunctuationDatasetCleaner
      punctuation: '!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~'
    re_tweet:
      _target_: jeffrey.data_processing.dataset_cleaners.ReTweetDatasetCleaner
    referance:
      _target_: jeffrey.data_processing.dataset_cleaners.ReferanceToAccountDatasetCleaner
    stop_words:
      _target_: jeffrey.data_processing.dataset_cleaners.StopWordsDatasetCleaner
    to_lower_case:
      _target_: jeffrey.data_processing.dataset_cleaners.ToLowerCaseDatasetCleaner
    url:
      _target_: jeffrey.data_processing.dataset_cleaners.URLDatasetCleaner
dataset_reader_manager:
  _target_: jeffrey.data_processing.dataset_readers.DatasetReaderManager
  available_memory: 3750000000.0
  dataset_readers:
    ghc:
      _target_: jeffrey.data_processing.dataset_readers.GHCDatasetReader
      data_version: v3
      dataset_dir: ./data/raw/ghc
      dataset_name: ghc
      dvc_remote_repo_address: https://github.com/jihoahn9303/data-versioning.git
      gcp_project_id: e2eml-jiho-430901
      gcp_secret_id: jeffrey-data-github-access-token
      secret_version_id: '1'
      split_ratio: 0.2
      user_name: jihoahn9303
    jtc:
      _target_: jeffrey.data_processing.dataset_readers.JigsawToxicCommentsDatasetReader
      data_version: v3
      dataset_dir: ./data/raw/jigsaw-toxic-comment
      dataset_name: jtc
      dvc_remote_repo_address: https://github.com/jihoahn9303/data-versioning.git
      gcp_project_id: e2eml-jiho-430901
      gcp_secret_id: jeffrey-data-github-access-token
      secret_version_id: '1'
      split_ratio: 0.03
      user_name: jihoahn9303
    twitter:
      _target_: jeffrey.data_processing.dataset_readers.TwitterDatasetReader
      data_version: v3
      dataset_dir: ./data/raw/twitter
      dataset_name: twitter
      dvc_remote_repo_address: https://github.com/jihoahn9303/data-versioning.git
      gcp_project_id: e2eml-jiho-430901
      gcp_secret_id: jeffrey-data-github-access-token
      secret_version_id: '1'
      test_split_ratio: 0.1
      user_name: jihoahn9303
      valid_split_ratio: 0.125
  repartition: true
docker_image_name: asia-northeast3-docker.pkg.dev/e2eml-jiho-430901/cyberbullying/data-processing
docker_image_tag: 8efccafe-80f0-4cb6-8db6-e8438ee58358
dvc_data_folder: data/raw
dvc_remote_repo: https://github.com/jihoahn9303/data-versioning.git
github_access_token_secret_id: jeffrey-data-github-access-token
github_user_name: jihoahn9303
infrastructure:
  network: default
  project_id: e2eml-jiho-430901
  secret_version: '1'
  zone: asia-northeast3-c
min_words: 2
processed_data_save_dir: gs://jeffrey-data-versioning/data/processed/rebalanced_splits
run_tag: rebalanced_splits
