defaults:
  - dataset_reader_manager_schema
  # {target folder contains target yaml file}@{config name in dataclass}.{arbitrary group name}: {name for target yaml file}
  - dataset_reader@dataset_readers.ghc: ghc
  - dataset_reader@dataset_readers.jtc: jtc
  - dataset_reader@dataset_readers.twitter: twitter

available_memory: 3.75e9